spring:
  datasource:
    url: ${MYSQL_DEV_URL}  # MySQL 데이터베이스 URL
  data:
    redis:
      host: localhost
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google  # /oauth2/authorization/google 로그인 시작 URL
          github:
            client-id: ${GITHUB_DEV_CLIENT_ID}
            client-secret: ${GITHUB_DEV_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/api/auth/github/callback
#      provider:
#        google:
#          authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#          token-uri: https://oauth2.googleapis.com/token
#          user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#          user-name-attribute: sub


jwt:
  access-expired: 28800  # 8시간
  refresh-expired: 86400  # 1일

app:
  front-url: http://localhost:3000
  cookie:
    secure: false
    same-site: Lax