spring:
  data:
    redis:
      port: 6379
      timeout: 2000
      password:
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      connection-timeout: 30000  # 30초 연결 제한
  #  h2:
  #    console:
  #      enabled: true  # H2 웹 콘솔 활성화
  #      path: /h2-console  # H2 콘솔 URL 경로 (기본값: /h2-console)
  jpa:
    show-sql: true  # SQL 로그 출력
    hibernate:
      ddl-auto: create # create # update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true  # SQL 로그를 보기 좋게 포맷
        auto_quote_keyword: true  # 예약어를 자동으로 따옴표 처리
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email, repo
  profiles:
    active: dev, s3Bucket  # logback-spring SpringProfile 설정 및 AWS S3 Bucket 설정

db:
  crypto-key: ${CRYPTO_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}
