server:
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${MYSQL_PROD_URL}  # MySQL 데이터베이스 URL
  data:
    redis:
      host: gitdeun-redis
      password: ${REDIS_PASSWORD}


jwt:
  access-expired: 1800 # 30분(초 단위: 0.5 * 60 * 60)
  refresh-expired: 604800  # 7일(초 단위: 7 * 24 * 60 * 60)

app:
  cookie:
    secure: true
    same-site: None