cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false # CloudFormation 스택 자동 생성을 비활성화
    s3:
      bucket:
        name: gitdeun

spring:
  config:
    activate:
      on-profile: s3Bucket
